-- Drop the database if it exists and create a new one
DROP DATABASE IF EXISTS customer_behavior;
CREATE DATABASE customer_behaviour;
use  customer_behaviour;
select * from customer;

 -- Q1:what is the total revenue generated by male vs female customers?
 select gender,sum(purchase_amount) as revenue from customer group by gender;
 
  -- Q2:which customer used discount but still spend more than the average user amount?
    select * from customer where discount_applied="Yes" and purchase_amount>(select avg(purchase_amount) from customer);

 

-- Q3:what are the top 5 products with highest average review ratings?
select item_purchased,avg(review_rating) as avg_review from customer group by item_purchased order by item_purchased desc limit 5;

-- Q4: compare the average purchase amount between standard and express shipping..?
select * from customer;
select shipping_type,avg(purchase_amount) from customer where shipping_type in('Express','Free Shipping') group by shipping_type;
  -- Q5 : Do subscribed customer spend more? Compare average spend and total revunue  between  subscribers and non-subscribers?
select avg(purchase_amount),sum(purchase_amount),subscription_status,count(customer_id) as total_customer from customer group by subscription_status;

  -- Q6 : which 5 products have the highest percentage of purchase with  discount applied?
select item_purchased,
sum(case when discount_applied="Yes" then 1 else 0 end)*100/count(*) as discount_applied
 from customer group by item_purchased
 order by discount_applied desc limit 5;
 
 -- Q7:segement customers into new,returning  and loyal based  on thier total number of previous purchase and show the count of each segement
 select count(*),
 case when previous_purchases=1 then "new" when previous_purchases<=5 then "returning" else "loyal" end
as customer_type
from customer
 group by customer_type;

 -- Q8:what are the top 3 top most purchased products within each category.
 
 SELECT category, item_purchased, purchase_count
FROM (
    SELECT 
        category,
        item_purchased,
        COUNT(*) AS purchase_count,
        ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(*) DESC) AS rank_no
    FROM customer
    GROUP BY category, item_purchased
) ranked
WHERE rank_no <= 3
ORDER BY category, purchase_count DESC;

SELECT category, item_purchased, COUNT(*) AS total_purchases
FROM customer
GROUP BY category, item_purchased
ORDER BY category, total_purchases DESC;

select * from customer;
-- Q9: Are customers who are repeat buyers (more than 5 previous purchase) also likely to subscribe?

select case when previous_purchases>5 then "repeat_customer" else "new customer" end as customer_type,
sum(case when subscription_status="Yes" then 1 else 0 end)*100/count(*) as subscription_type,
count(*) as no_of_customer from customer group by customer_type;

-- Q10: Revenue contribution of each age group
select sum(purchase_amount) as contribution,age from customer group by age order by contribution desc;



SELECT
    CASE 
        WHEN previous_purchases > 5 THEN 'Repeat Buyer'
        ELSE 'Non-Repeat Buyer'
    END AS customer_type,
    SUM(CASE WHEN subscription_status = 'Yes' THEN 1 ELSE 0 END) * 100.0 / COUNT(*) AS subscription_rate
FROM customer
GROUP BY customer_type;


    
   -- List all unique product categories available.
   select distinct(category) from customer;
   -- Find the total purchase amount by each category.
   select category,avg(purchase_amount) from customer group by category;
   
   -- Find average purchase amount by gender.
   select gender,avg(purchase_amount) from customer group by gender;
  
   -- Count how many customers applied a discount.
   select count(*) as customer_applied from customer where discount_applied="Yes";
   

-- Find top 5 locations with the highest total purchase amount.
select location,sum(purchase_amount) as total_purchase from customer group by location order by total_purchase desc limit 5;

-- Find average review rating for each product category.
select category,avg(review_rating) from customer group by category;

-- Find total purchases made in each season.
select season,sum(purchase_amount) from customer group by season;

-- Find how many customers subscribed vs not subscribed.
select subscription_status,count(*) as total_customer from customer group by subscription_status;

-- Find correlation between number of previous purchases and purchase amount (average per group).
select previous_purchases,avg(purchase_amount) as avg_purchase_amount from customer  group by previous_purchases order by previous_purchases;

select * from customer;
-- Find the most popular payment method.
select payment_method,count(*) as usage_count from customer group by payment_method order by usage_count desc limit 1;

-- Day 2
-- Show gender-wise total purchase amount only for those who applied discounts
select gender,sum(purchase_amount) from customer where discount_applied='Yes' group by gender;


-- Find categories where the average purchase amount is above ₹500
select avg(purchase_amount) as avg_purchase,category from customer group by category having avg_purchase>500;

-- Find locations where more than 50 customers made purchases.
select location,count(*) as no_of_customer from customer where previous_purchases>10 group by location ;

-- Show each customer’s type as ‘Repeat Buyer’ if previous_purchases > 5, else ‘New Buyer’.
select case when previous_purchases>5 then 'Repeat_Buyer' else 'New_Buyer' end as customer_type,count(*) as no_of_customer 
from customer group by customer_type ;

-- Find the most common shipping type used for each gender
SELECT gender, shipping_type
FROM (
  SELECT gender, shipping_type, 
         COUNT(*) AS type_count,
         RANK() OVER (PARTITION BY gender ORDER BY COUNT(*) DESC) AS rnk
  FROM customer
  GROUP BY gender, shipping_type
) ranked
WHERE rnk = 1;


-- List all customers whose purchase amount is greater than the overall average purchase amount
select * from customer where purchase_amount>(select avg(purchase_amount) from customer);

-- Find product categories where more than 70% of customers left a review rating of 4 or higher
select category,sum(case when review_rating>4 then 1 else 0 end)*100/count(*) as review_percent from customer  group by  category having review_percent>70;

-- Show total purchase amount by season, but only for Express shipping type.
select sum(purchase_amount),season,shipping_type from customer where shipping_type in('Express')  group by season;

select * from customer;
-- Find the top 3 product categories by average review rating.
select category,avg(review_rating) as avg_rating from customer group by category order by avg_rating desc limit 3;

-- Show, for each payment method, the percentage of customers who applied discounts.
select payment_method,sum(case when discount_applied="Yes" then 1 else 0 end)*100/count(*) as percent_of_disc_applied from customer group by payment_method;


-- Find the most common shipping type used for each gender

select gender,shipping_type,no_of_customer from(
select gender,shipping_type,count(*) as no_of_customer,row_number() over(partition by gender order by count(*) desc) as rnk
from customer group by gender,shipping_type)ranked where rnk=1;

-- rank all the shipping_type from max preferred to least preferred based on gender
   
select gender,shipping_type,count(*) as no_of_customer,row_number() over(partition by gender order by count(*) desc) as rnk from customer group by gender,shipping_type;

   
-- Find the top 3 locations with the highest average purchase amount, but only include locations where more than 20 customers have made purchases.
select location,avg(purchase_amount) as avg_purchase
,count(*) as no_of_customer
from customer group by location having count(*)>20 order by  avg_purchase desc limit 3;



-- Show the average review rating by season, but only for customers who did not apply a discount.
select season,avg(review_rating) from customer where discount_applied='No'
 group by season;
 

 
 -- Q23.Find the most common category in each season (i.e., the category with the highest number of purchases per season).
 select category,season,most_purchased
 from
 (select category,count(*) as most_purchased,
 season,row_number() over(partition by season
 order by count(*) desc) as rnk from customer group by category,season)ranked 
where rnk=1;

-- Show for each gender, the percentage of customers who subscribed
select gender,sum(case when subscription_status='Yes' then 1 else 0 end)*100/count(*) as perc_of_subscription from customer group by gender;
 select * from customer;
-- Show, for each payment method, the average purchase amount and average review rating, sorted by highest average purchase amount.
select avg(purchase_amount) as avg_purchase,
avg(review_rating),
payment_method from customer group by payment_method
order by avg_purchase desc;

-- For each category, find the difference between the maximum and minimum purchase amount.
select category,max(purchase_amount)-
min(purchase_amount) as purchase_diff
from customer group by category;

-- Find the most popular combination of (category, payment_method) by total number of customers.
select category,
payment_method,
count(*) as no_of_customer from customer
 group by category, payment_method
order by no_of_customer desc limit 1;
-- Find the most popular combination of (category, payment_method) by total number of customers(repeat using rank)
select category,payment_method,no_of_customer from
(select category,payment_method,count(*) as no_of_customer,rank() over(order by count(*) desc) as rnk 
from customer group by category, payment_method)ranked where rnk=1;

-- Find the most popular combination of (category, payment_method) by total number of customers(repeat using rownumber)
select category,payment_method,no_of_customer from(select category,payment_method,count(*) as no_of_customer,
row_number() over(order by count(*) desc) as rnk from customer group by category, payment_method)ranked where rnk=1;

-- Show the cumulative total purchase amount by season, ordered by season name alphabetically.
SELECT 
  season,
  season_total,
  SUM(season_total) OVER (ORDER BY season) AS cumulative_total
FROM (
  SELECT season, SUM(purchase_amount) AS season_total
  FROM customer
  GROUP BY season
) t
ORDER BY season;

-- Find customers whose purchase_amount falls in the top -0% of all purchases
SELECT *
FROM (
  SELECT *,
         NTILE(10) OVER (ORDER BY purchase_amount DESC) AS decile
  FROM customer
) ranked
WHERE decile = 1;


